name: Flutter
on:
  push:
    branches: [ "test-report" ]
  pull_request:
    branches: [ "test-report" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: apt-get -y install lcov
    - run: flutter test --coverage
    - run: genhtml coverage/lcov.info -o coverage/html
    - uses: actions/upload-artifact@v3
      with:
        name: Coverage
        path: ./coverage/html/index.html

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' 
    - run: flutter pub get
    - run: flutter build web
    - run: ls
    - uses: actions/upload-artifact@v3
      with:
        name: Build
        path: ./build/web/*
